### ISSUE TITLE
Errors after change to 1.0.7

### ISSUE THREAD

**Issue by focussing** [mayasabha/ckeditor4-vue3#13]
Hello!

I changed the version of this plugin from 1.0.5 to 1.0.7 and now I suddenly get some error messages in the console:

![tempsnip](https://github.com/mayasabha/ckeditor4-vue3/assets/26736152/b4c9ce4a-c026-457f-a2ca-cc818eb4f9ba)

What is happening?

Best regards,
Raymond

**Comment by apoorvpal01** [comment]
The console error seems to be something on the CKEditor CDN because it is from the ckeditor.js file fetched from the server. I believe they have fixed the issue.

For the alert notification @lserio , this has been added by the CKEditor team indicating the EOL. You can add a `versionCheck: false` to the editor config to fix this. [Ref](https://stackoverflow.com/questions/77959273/ckeditor-4-22-1-error-throws-an-error-regarding-version-is-not-secure) . You can also update to 1.0.8, which I'll release in a short while, which has this attribute defaulting to false, when not specified explicitly

**Comment by focussing** [comment]
Would it be possible not to use the CDN but put the whole Ckeditor4 package locally?
If so how to do that?

**Comment by apoorvpal01** [comment]
@focussing The `editorUrl` prop can be used to specify a custom ckeditor.js file. The path needs to be a URL which can be accessed over the web though, and cannot be something that you only use during your frontend compilation. The ckeditor.js has to be a static asset present on your site, and you can use the link to it in the `editorUrl` prop.
